{% set name = "ctc-segmentation" %}
{% set version = "1.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ctc_segmentation-{{ version }}.tar.gz
  sha256: 19d383ea5f22438ebb1699d72b22078b63f351a33fa50bedb19c14077ba6a116

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ctc_segmentation

about:
  home: https://github.com/lumaku/ctc-segmentation
  summary: CTC segmentation to align utterances within large audio files.
  description: CTC segmentation is used to align utterances within audio files. It can be combined with CTC-based ASR models. This package includes the core functions.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wietsedv
